# version: '3'

# services:
#   survey:
#     build: survey_server/
#     depends_on:
#       - 'database'
#     ports: 
#       - '8080:8080'

#   results:
#     build: results_server/
#     depends_on:
#       - 'database'
#     ports:
#       - '3000:3000'

#   database:
#     image: mongo:latest

version: "3.9"
services:
  database:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db

  results:
    build:
      context: ./results
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_PORT=27017

  survey:
    build:
      context: ./survey
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_PORT=27017

volumes:
  db_data:

